### ISSUE TITLE
File Validation error

### ISSUE THREAD

**Issue by slier81** [thedevsaddam/govalidator#15]
Using your example
```
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
		"stock_image": []string{"ext:jpg,jpeg,png,bmp", "size:20000000", "required"},
	}

	opts := govalidator.Options{
		Request: r,     // request object
		Rules:   rules, // rules map
	}
	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	fmt.Fprintln(w, err)

}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9000")
	http.ListenAndServe(":9000", nil)
}
```

always yield me to `map[validationError:map[stock_image:[The stock_image field is required]]]` even though i already select a file to be upload.

I think the problem is in `validator.go line 87` (v.Opts.Request.Form.Get) , since its files, its not available in `v.Opts.Request.Form` instead available in `v.Opts.RequestMultiPartForm`

Thats why `validateCustomRules(field, rule, msg, reqVal, errsBag)` always return an error, since `reqVal` always empty

**Comment by slier81** [comment]
@thedevsaddam i think there i a bug in the implementation

```
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
		"stock_image": []string{"ext:jpg,jpeg,png,bmp", "size:20000000"}, //notice there is no "required"
	}

	opts := govalidator.Options{
		Request: r,     // request object
		Rules:   rules, // rules map
	}
	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	fmt.Fprintln(w, err)

}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9000")
	http.ListenAndServe(":9000", nil)
}
```

The validator still run eventhough im not explicitly set the rules as `"required"`

**Comment by thedevsaddam** [comment]
@slier81 Are you using version 1.6?

**Comment by slier81** [comment]
@thedevsaddam yes im using version 1.6
But according to your [documentation](https://github.com/thedevsaddam/govalidator/blob/master/doc/FILE_VALIDATION.md) `When validation multipart/form-data using Validate method you must use a required tag rule for file validation.` 

I guess i cant have optional validation for file.Am i right?

**Comment by thedevsaddam** [comment]
@slier81 What do you think, if we use `file-required` rule instead of `required`

**Comment by slier81** [comment]
@thedevsaddam Imho , for consistency , using `required` is a better way. Will u implement this? i thought when validating files, i need `required` rules

**Comment by slier81** [comment]
@thedevsaddam may i know the status? will u implement optional rules for files?

**Comment by thedevsaddam** [comment]
@slier81 I'm working on it. hopefully, it'll fix soon

**Comment by slier81** [comment]
@thedevsaddam thx!

**Comment by slier81** [comment]
@thedevsaddam u should update the doc regarding custom message for files too

```
	messages := govalidator.MapData{
		"file:photo": []string{"ext:Only jpg,png is allowed", "required:Photo is required"}
               //This wont work anymore
              //"photo": []string{"ext:Only jpg,png is allowed", "required:Photo is required"}
	}

	rules := govalidator.MapData{
		"file:photo": []string{"ext:jpg,pdf", "size:10000", "required"},
	}

	opts := govalidator.Options{
		Request: r,     // request object
		Rules:   rules, // rules map
		Messages: messages, //rules messages
	}

	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "applciation/json")
	json.NewEncoder(w).Encode(err)
```

**Comment by thedevsaddam** [comment]
@slier81 Thank you very much, I really appreciate your help for this package and specially for this issue.  I'll update the doc soon.
