### ISSUE TITLE
How about set default value for field in struct?

### ISSUE THREAD

**Issue by jkryanchou** [thedevsaddam/govalidator#16]
How about setting default value by providing default struct tag to set default value when the field was null in validation phrase. As below `Username` and `Email` fields
```
type user struct {
	Username string           `json:"username",default:"foo"`
	Email    string           `json:"email",default:"foo@bar.com"`
	Web      string           `json:"web"`
	Age      govalidator.Int  `json:"age"`
	Agree    govalidator.Bool `json:"agree"`
}

rules := govalidator.MapData{
	"username": []string{"required", "between:3,8"},
	"email":    []string{"required", "min:4", "max:20", "email"},
	"web":      []string{"url"},
	"phone":    []string{"digits:11"}
	"agree":    []string{"bool"},
	"dob":      []string{"date"},
}

opts := govalidator.Options{
	Request:         &user{Username: "test",  ....},        // use struct instead net.http
	Rules:           rules,    // rules map
	Messages:        messages, // custom message map (Optional)
	RequiredDefault: true,     // all the field to be pass the rules
} 
```

**Comment by thedevsaddam** [comment]
@jkryanchou Probably this is not a validator's responsibility

**Comment by jkryanchou** [comment]
@stevehill1981 OK, Thanks.  I have already found out the way to set default value for fields by chaining with defaults library https://github.com/creasty/defaults.

**Comment by stevehill1981** [comment]
I didn't know about that other library, but it's awesome so thanks for the link :)

**Comment by jkryanchou** [comment]
@stevehill1981 Yeah. I have searched for a long time on the issue. The library which could provide another choices on schema-validation show a better way to handle that.

The example shows that we could chain the go library such as `govalidator | mold | form ` together  into struct tags. Wish it could help U. It is a better solution on it.
