### ISSUE TITLE
Custom rule not applied to file's validation

### ISSUE THREAD

**Issue by erickskrauch** [thedevsaddam/govalidator#18]
I want to validate file by my own validator, but [by current implementation](https://github.com/thedevsaddam/govalidator/blob/f3a2b50d2d05ad0ce4b1c4e395ba976db0c050b6/validator.go#L92-L107), it is not possible because custom validation can be applied only to required files, that not uploaded (what?!).

**Comment by thedevsaddam** [comment]
@erickskrauch Thank you very much! I really appreciate you for this **PR**, hope you'll help to find out and fix next bug 👍

**Comment by erickskrauch** [comment]
Was glad to help.
