### ISSUE TITLE
Any way to validate raw POST data, type application/json or text/json

### ISSUE THREAD

**Issue by s4kibs4mi** [thedevsaddam/govalidator#2]

**Comment by thedevsaddam** [comment]
**Yes, you can validate raw post data ( application/json or text/json).**
See example (these example is validating the raw post body application/json, text/json): 
1.  [Validate JSON to simple struct](https://github.com/thedevsaddam/govalidator/blob/master/doc/SIMPLE_STRUCT_VALIDATION.md)
2. [Validate JSON to map](https://github.com/thedevsaddam/govalidator/blob/master/doc/MAP_VALIDATION.md)

**Comment by gayanhewa** [comment]
@thedevsaddam  curious why we have used `govalidator.Int` in the struct. Does it have any impact if I opt to use the standard go types?
