### ISSUE TITLE
File validation not working?

### ISSUE THREAD

**Issue by slier81** [thedevsaddam/govalidator#24]
Hey adam..

I think the form validation is not working when the rules is optional (no `required`)
```
func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
                //Notice this rules is optional
		"file:photo": []string{"ext:jpg,png", "size:2000000", "mime:jpg,png"},
	}

	messages := govalidator.MapData{
		"file:photo": []string{"ext:Only jpg/png is allowed", "size:Maximux size is 2Mb"},
	}

	opts := govalidator.Options{
		Request: r,     // request object
		Rules:   rules, // rules map,
		Messages: messages,
	}

	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "applciation/json")
	json.NewEncoder(w).Encode(err)
}

```

Eventhough im not uploading any file, the validation still run through yielding me to `Only jpg/png is allowed`

Regarding this line:
[https://github.com/thedevsaddam/govalidator/blob/master/validator.go#L95](https://github.com/thedevsaddam/govalidator/blob/master/validator.go#L95)

Even though there is no uploaded file, `file` is still not nil
I think the correct way should be

```
if strings.HasPrefix(field, "file:") {
	fld := strings.TrimPrefix(field, "file:")
	file, fileHeader, _ := v.Opts.Request.FormFile(fld)
	if fileHeader.Filename  != "" {
		validateFiles(v.Opts.Request, fld, rule, msg, errsBag)
		validateCustomRules(fld, rule, msg, file, errsBag)
	} else {
		validateCustomRules(fld, rule, msg, nil, errsBag)
	}
}
```

Some additional info:
Golang v1.10
I'm entirely not sure prior to v1.10 whether its working or not

**Comment by thedevsaddam** [comment]
### Go version:
```bash
go version go1.10 darwin/amd64
```

## Code
```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
		"file:photo": []string{"ext:jpg,png", "size:10000", "mime:jpg,png"},
	}

	messages := govalidator.MapData{
		"file:photo": []string{"ext:Only jpg/png is allowed", "required:Photo is required"},
	}

	opts := govalidator.Options{
		Request:  r,     // request object
		Rules:    rules, // rules map,
		Messages: messages,
	}
	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "applciation/json")
	json.NewEncoder(w).Encode(err)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9999")
	http.ListenAndServe(":9999", nil)
}
```

### Response:
Without providing any file
<img width="1125" alt="screen shot 2018-02-19 at 5 54 15 pm" src="https://user-images.githubusercontent.com/9676798/36376633-f611c2de-159d-11e8-805c-e8d1ed204faa.png">

> Could you please provide me more details. @slier81 It seem's okay

**Comment by slier81** [comment]
@thedevsaddam ill double check, will inform u afterward

**Comment by slier81** [comment]
@thedevsaddam 

I can sure you that the bug really exist.
I dont know why you didnt get the error when u run it throught `postman`

```
package main

import (
	"fmt"
	"net/http"
	"text/template"
	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {

	if r.Method == "GET" {
		t, _ := template.New("foo").Parse(`
			<html><form action="/" method="post" enctype="multipart/form-data">
				<input type="file" name="photo">
				<input type="submit">
    		        </form></html>
		`)

		t.Execute(w, nil)

	} else {
		rules := govalidator.MapData{
			"file:photo": []string{"ext:jpg,png", "size:10000000"},
		}

		messages := govalidator.MapData{
			"file:photo": []string{"ext:Only jpg/png is allowed", "required:Photo is required"},
		}

		opts := govalidator.Options{
			Request:  r,     // request object
			Rules:    rules, // rules map,
			Messages: messages,
		}
		v := govalidator.New(opts)
		e := v.Validate()
		err := map[string]interface{}{"validationError": e}
		fmt.Fprint(w, err)
	}
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 8000")
	http.ListenAndServe(":8000", nil)
}
```
When u submit the form without uploading any file, u will get `map[validationError:map[photo:[Only jpg/png is allowed]]]`


Another bug, when u explicitly put `required` rules and submit the form without uploading any files, the `required` rules seems not being apply.It will return `map[validationError:map[photo:[Only jpg/png is allowed]]]`

**Comment by thedevsaddam** [comment]
@slier81 Yes, you are right. Could you please send a PR to fix this issue in `dev` branch :)

**Comment by thedevsaddam** [comment]
@slier81  Hope it'll work now. Please check from master branch and if it's okay then I'll tag this commit as `v1.9`

**Comment by slier81** [comment]
@thedevsaddam eh i thought u waiting for my PR? nvm ill check it, and confirm with u afterwards

**Comment by slier81** [comment]
@thedevsaddam Yes everything is working as expected.Thank you for your hard work..You can tag this commit as `v1.9` and close this issue
