### ISSUE TITLE
validator throws a "required field" error even if the data is present in the payload

### ISSUE THREAD

**Issue by rahulxxarora** [thedevsaddam/govalidator#43]
Hi, I have recently started using the govalidator library and I must say this has solved a lot of problems for me.

I am trying to validate the following request but I am getting an error. Could you please let me know if it's a bug or am I doing something wrong?

payload: {"user":"uewbf937rweab", "data": {"event": "cm", "messages": "[\"Hello to the world!\"]"}}

rules: govalidator.MapData{
			"user": []string{"required"},
			"data": []string{"required"},
		}

error: "the data field is required"

**Comment by thedevsaddam** [comment]
Can you share more details, snippet of your validation code

**Comment by rahulxxarora** [comment]
Hey, I am sorry. I forgot to mention that the required flag was on in the rules map. Does this make it easier for you to understand?

**Comment by rahulxxarora** [comment]
Below is my validation middleware


    func Validator(next httpHandlerFunc) httpHandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rules := validations.GetRules(r)
		requestData := make(map[string]interface{})

		opts := govalidator.Options{
			Request: r,
			Rules:   rules,
			Data:    &requestData,
		}

		validator := govalidator.New(opts)
		var error url.Values

		if r.Method == "GET" {
			error = validator.Validate()
		} else {
			error = validator.ValidateJSON()
		}

		if len(error) != 0 {
			response, _ := json.Marshal(map[string]interface{}{"status": "failure", "error": error})
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(400)
			w.Write(response)
			return
		}

		context.Set(r, "requestData", requestData)
		next(w, r)
	}
    }
`
@thedevsaddam

**Comment by thedevsaddam** [comment]
@rahulxxarora Sorry for the inconvenience, I forget to mention that you have to check the last property for the required rule. It would be great if someone sends a PR to enhance the **required** rule.

You can require the "event, messages".

Here is an example:

```go

package main

import (
	"encoding/json"
	"log"
	"net/http"
	"net/url"

	"github.com/thedevsaddam/govalidator"
)

const port = ":8888"

func main() {

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		rules := govalidator.MapData{
			"user":     []string{"required"},
			"messages": []string{"required"},
		}

		requestData := make(map[string]interface{})

		opts := govalidator.Options{
			Request: r,
			Rules:   rules,
			Data:    &requestData,
		}

		validator := govalidator.New(opts)
		var error url.Values

		if r.Method == "GET" {
			error = validator.Validate()
		} else {
			error = validator.ValidateJSON()
		}

		if len(error) != 0 {
			response, _ := json.Marshal(map[string]interface{}{"status": "failure", "error": error})
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(400)
			w.Write(response)
			return
		}
	})
	log.Println("Listening on port", port)
	http.ListenAndServe(port, nil)
}

```

**Comment by rahulxxarora** [comment]
Thanks for letting me know about this.
