### ISSUE TITLE
email required when no required rule is set

### ISSUE THREAD

**Issue by g13013** [thedevsaddam/govalidator#47]
these rules

```go

	rules := govalidator.MapData{
		"mail1":   []string{"required", "email"},
		"mail2":      []string{"email"},
	}
```
give me `mail2` `The sender field must be a valid email address`

I think that the correct behavior should be that the validation allows empty emails

**Comment by thedevsaddam** [comment]
If you are validating `form-data` this code should work.

```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
		"email": []string{"email"},
	}

	opts := govalidator.Options{
		Request:         r,     // request object
		Rules:           rules, // rules map
		RequiredDefault: false, // all the field to be pass the rules
	}
	v := govalidator.New(opts)
	e := v.Validate()
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "application/json")
	json.NewEncoder(w).Encode(err)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9999")
	http.ListenAndServe(":9999", nil)
}

```

and if you are validating `json payload` this code should work:

```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/thedevsaddam/govalidator"
)

func handler(w http.ResponseWriter, r *http.Request) {
	rules := govalidator.MapData{
		"email": []string{"email"},
	}

	data := struct {
		Email string `json:"email"`
	}{}

	opts := govalidator.Options{
		Request:         r,     // request object
		Rules:           rules, // rules map
		Data:            &data,
		RequiredDefault: false, // all the field to be pass the rules
	}
	v := govalidator.New(opts)
	e := v.ValidateJSON()
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "application/json")
	json.NewEncoder(w).Encode(err)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9999")
	http.ListenAndServe(":9999", nil)
}


```

Go Version: go version go1.10.3 darwin/amd64
Govalidator:  v1.9.1

**Note: If the field is present and the value is empty/invalid then the validator will throw an error. But if the field is absent in payload then it will not throw validation error.**

**Comment by jos-** [comment]
For form data, it's much more convenient if input can be validated only if non-empty.

It would be great if there were a `nullable` rule for optional fields, such as Laravel has.

**Comment by IvanDelsinne** [comment]
I'm stuck with the same problem for the `url` validation type on an *optional* field.

I always obtain validation errors because the field is empty while I only gave the `url` validator (`"PersonalWebsite": []string{"url"},`).

**Comment by thedevsaddam** [comment]
@jos- This would be more convenient if the field is present then apply validation rule, otherwise (field absent) skip the validation rule.

**Comment by thedevsaddam** [comment]
> I'm stuck with the same problem for the `url` validation type on an _optional_ field.
> 
> I always obtain validation errors because the field is empty while I only gave the `url` validator (`"PersonalWebsite": []string{"url"},`).

Remove the if empty from client end, if the field present in the body then it'll be stuck by validation rule

**Comment by IvanDelsinne** [comment]
> Remove the field if empty from client end, if the field present in the body then it'll be stuck by validation rule

That seems hacky imo, and that also means that you'd have to do a first request form handling round to build a temporary `url.Values` set of non-empty fields.

(after trying out a few existing validation libraries, I built my own, which does the job for me)

**Comment by h86ceccx4stxm1h** [comment]
i have field "between:100,200" but cant be optional. agree would like nullable option
