### ISSUE TITLE
digits:int goes scientific at 13 digits

### ISSUE THREAD

**Issue by setheen** [thedevsaddam/govalidator#48]
rule `digits:12`, no problem.  rule `digits:13` ends up taking a 13 digit integer and formatting to scientific notation, resulting in a string length of 15.  Example:

```
rules := govalidator.MapData{ "createdEpochMs": []string{"required", "digits:13"} }
```
when passing `1541689038000` to [rules:go:toString(value)](https://github.com/thedevsaddam/govalidator/blob/master/rules.go#L453), a string value of `1.541689038e+12` is returned. [utils:go:toString(value)](https://github.com/thedevsaddam/govalidator/blob/master/utils.go#L40) formats `interface{}` to "%#v" which exceeds the default width.

Considering you know the intended length "l" based on the "digits:" suffix and that it's an integer type, one possible approach to resolve this might be to use an explicit width format on an alternate "toString" method:
```
func toNumericString(v interface{}, width int, precision int) string {
	str, ok := v.(string)
	if !ok {
		format := fmt.Sprintf("%%%d.%df", width, precision)
		str = fmt.Sprintf(format, v)
	}
	return str
}
```
This is what the call would look like:
```
str := toNumericString(value, l, 0)
if len(str) != l || !isNumeric(str) {
	return err
}
```

There may be even simpler ways to do it.  Just looking to validate an epoch in milliseconds.  I will likely fall back on regex validation for the time-being.

**Comment by setheen** [comment]
Looks like custom rule "regex" succumbs to the same formatting issue

**Comment by thedevsaddam** [comment]
@setheen Did you find any solution for this. I wish you send a PR :)

**Comment by thedevsaddam** [comment]
@setheen Hope this issue is solved 👍
