### ISSUE TITLE
Implement translation message

### ISSUE THREAD

**Issue by nipeharefa** [thedevsaddam/govalidator#60]
Hi, 
Any plan to implement translation message on this package?

**Comment by cyruzin** [comment]
```
messages := govalidator.MapData{
		"username": []string{"required:আপনাকে অবশ্যই ইউজারনেম দিতে হবে", "between:ইউজারনেম অবশ্যই ৩-৮ অক্ষর হতে হবে"},
		"phone":    []string{"digits:ফোন নাম্বার অবশ্যই ১১ নম্বারের হতে হবে"},
	}
```

**Comment by thedevsaddam** [comment]
@nipeharefa It would be great if the package support translation, can you please share some more information on how this can be achieved?

You can use `MapData` to translate the validation errors like @cyruzin shared an example.
