### ISSUE TITLE
date validation fails for date:dd-mm-yyyy.

### ISSUE THREAD

**Issue by anant-barlota** [thedevsaddam/govalidator#70]
// Date check the provided field is valid Date
	AddCustomRule("date", func(field string, rule string, message string, value interface{}) error {
		str := toString(value)
		if rule == "date:dd-mm-yyyy" {
			if !isDateDDMMYY(str) {
				if message != "" {
					return errors.New(message)
				}
				return fmt.Errorf("The %s field must be a valid date format. e.g: dd-mm-yyyy, dd/mm/yyyy etc", field)
			}
		}
		if !isDate(str) {
			if message != "" {
				return errors.New(message)
			}
			return fmt.Errorf("The %s field must be a valid date format. e.g: yyyy-mm-dd, yyyy/mm/dd etc", field)
		}
		return nil
	})

This is inherently flawed, when the following check passes without any error it should return from there, 

    		if rule == "date:dd-mm-yyyy" {
			if !isDateDDMMYY(str) {
				if message != "" {
					return errors.New(message)
				}
				return fmt.Errorf("The %s field must be a valid date format. e.g: dd-mm-yyyy, dd/mm/yyyy etc", field)
			}
		}

instead it does the second check too

		if !isDate(str) {
			if message != "" {
				return errors.New(message)
			}
			return fmt.Errorf("The %s field must be a valid date format. e.g: yyyy-mm-dd, yyyy/mm/dd etc", field)
		}
		return nil
	})

A better solution would be 

	// Date check the provided field is valid Date
	AddCustomRule("date", func(field string, rule string, message string, value interface{}) error {
		str := toString(value)

		switch rule {
		case "date:dd-mm-yyyy":
			if !isDateDDMMYY(str) {
				if message != "" {
					return errors.New(message)
				}
				return fmt.Errorf("The %s field must be a valid date format. e.g: dd-mm-yyyy, dd/mm/yyyy etc", field)
			}
		default:
			if !isDate(str) {
				if message != "" {
					return errors.New(message)
				}
				return fmt.Errorf("The %s field must be a valid date format. e.g: yyyy-mm-dd, yyyy/mm/dd etc", field)
			}
		}
		return nil
	})

**Comment by thedevsaddam** [comment]
@anant-barlota Updating this block
