### ISSUE TITLE
Fields with string base types cannot be optional

### ISSUE THREAD

**Issue by RobvH** [thedevsaddam/govalidator#73]
The use case I'm presenting is what I'd consider the current-conventional use case. We're not submitting a form/url-encoded to the api end point, but rather posting application/json. Thus to validate the request, we have to pass a Go struct defining the data to the validator. When unmarshalling the JSON, all string fields on the struct will be assigned "" (empty string) if no value is present in the post body's JSON. This brings us to the various alpha* validation rules and "required". 

The problem is that empty string fails every string rule even when "required" isn't set as a rule on a field. 

How should we approach this?

**Comment by thedevsaddam** [comment]
Can you share some code snippet? 
I'm replying based on what I understand from the question.

```go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/thedevsaddam/govalidator"
)

// User ...
type User struct {
	Username string           `json:"username"`
	Email    string           `json:"email"`
	Web      string           `json:"web"`
	Age      govalidator.Int  `json:"age"`
	Agree    govalidator.Bool `json:"agree"`
}

func handler(w http.ResponseWriter, r *http.Request) {
	var user User
	rules := govalidator.MapData{
		"username": []string{"max:5"},
		"email":    []string{"required", "min:4", "max:20", "email"},
		"web":      []string{"url"},
		"age":      []string{"required"},
		"agree":    []string{"required"},
	}

	opts := govalidator.Options{
		Request: r,
		Data:    &user,
		Rules:   rules,
	}

	v := govalidator.New(opts)
	e := v.ValidateJSON()
	fmt.Println(user) // your incoming JSON data in Go data struct
	err := map[string]interface{}{"validationError": e}
	w.Header().Set("Content-type", "application/json")
	json.NewEncoder(w).Encode(err)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Listening on port: 9000")
	http.ListenAndServe(":9000", nil)
}

```

Let assume we set a rule `max:5` for `username` field, when submitting the post body without providing any value for username field we won't get any validation error for the field.

*Input*

```json
{
  "email":"mail@mail.com",
  "age": 30,
  "web":"https://www.google.com",
  "dob": "2019-10-11",
  "phone": "01731375076",
  "roles": ["admin", "user", "manager", "superadmin"],
  "address":{
  	"postalCode": "1233",
  	"village": "some village"
  }
}
```

*Output*
```json
{
    "validationError": {
        "agree": [
            "The agree field is required"
        ]
    }
}
```

But I we beak the rules providing more than 5 chars for the field we'll get error
*Input*
```json
{
  "username":"johndoe",
  "email":"mail@mail.com",
  "age": 30,
  "web":"https://www.google.com",
  "dob": "2019-10-11",
  "phone": "01731375076",
  "roles": ["admin", "user", "manager", "superadmin"],
  "address":{
  	"postalCode": "1233",
  	"village": "some village"
  }
}
```

*Output*

```json
{
    "validationError": {
        "agree": [
            "The agree field is required"
        ],
        "username": [
            "The username field must be maximum 5 char"
        ]
    }
}
```

**Comment by RobvH** [comment]
Firstly, thank you so much for your prompt reply. I was just about to edit to apologize for my ignorance. I stepped through the code and the problem was that `getNonRequiredJSONFields` wasn't returning these fields into `nr`; and the reason was `v.Opts.RequiredDefault` was set to `true` -- by me. A setting I placed right when I started out with this and had forgotten about. Lesson learned.
