### ISSUE TITLE
Max rule has incorrect message when validating slices

### ISSUE THREAD

**Issue by System-Glitch** [thedevsaddam/govalidator#86]
The `max` rule shows the following message when validating a **slice**:

    The %s field must be minimum %d in size

**Expected**

     The %s field must be maximum %d in size

[Ref](https://github.com/thedevsaddam/govalidator/blob/01bf6ba67ac42ba976ff56c550a95ad8010cfa3e/rules.go#L786)

**Comment by thedevsaddam** [comment]
Fixed the typo, use `v1.9.1`
