### ISSUE TITLE
Validating numeric field with value 0

### ISSUE THREAD

**Issue by Entrio** [thedevsaddam/govalidator#9]
When validating a field with rule "required" and "numeric", when the value of 0 is provided, required validation error is trigered.

Go version: 1.9
Framework: echo
Here is an example

### Json struct
>type serviceRequest struct {
	Owner            string `json:"owner"`
	Service          int    `json:"service"`
	Operation        string `json:"operation"`
	AgentTransaction string `json:"ati"`
}

### Here is the request handling function
> func AgentServiceAction(c echo.Context) (err error) {

	var structure serviceRequest
	rules := govalidator.MapData{
		"owner":     []string{"required", "between:10,16"},
		"service":   []string{"required", "numeric"},
		"operation": []string{"required", "in:start,confirm,check"},
		"ati":       []string{"required", "alpha_num", "max:64", "min:1"},
	}
	opts := govalidator.Options{
		Request: c.Request(), // request object
		Data:    &structure,  //Structure to validate
		Rules:   rules,       // rules map
	}

	v := govalidator.New(opts)
	e := v.ValidateJSON()

	fmt.Println(v)
	fmt.Println(e)

	verr := map[string]interface{}{"validationError": e}

	return c.JSON(200, response.JsonResponse{
		Code:    300,
		Message: "All good!",
		Data:    verr,
	})
}

### Post data:

> {
	"ati":"324t5fc45w6bh6r7unr758rtinr67",
	"operation":"start",
	"owner":"871029399119",
	"service":0
}

### The received response:

> {
    "code": 300,
    "success": false,
    "message": "All good!",
    "data": {
        "validationError": {
            "service": [
                "The service field is required"
            ]
        }
    }
}

**Comment by Entrio** [comment]
Is there an ETA on this?

**Comment by thedevsaddam** [comment]
@Entrio I am working on this in [fix-numeric branch](https://github.com/thedevsaddam/govalidator/tree/fix/numeric-field). Hopefully, it'll complete by next week.

**Comment by thedevsaddam** [comment]
@Entrio Here is a [fix](https://github.com/thedevsaddam/govalidator/blob/master/doc/SIMPLE_STRUCT_VALIDATION.md). Hope it'll work fine.
